apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-fail-
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command: 
          - curl -I -o /dev/null -s -w "%{http_code}" https://google.com | grep -q 200 || exit 1
      restartPolicy: Never
  backoffLimit: 2